name: fitness_quest
description: A fitness app with Spotify-inspired UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.1.2
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  provider: ^6.1.1
  pedometer: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  modal_bottom_sheet: ^3.0.0-pre
  cached_network_image: ^3.3.0
  table_calendar: ^3.0.9
  share_plus: ^7.2.1
  intl: ^0.19.0
  preload_page_view: ^0.2.0
  url_launcher: ^6.1.10
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4
  flutter_svg: ^2.0.9
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  firebase_storage: ^11.6.8
  firebase_analytics: ^10.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/gifs/
    - assets/icon/
